export const Tables = {
  user: 'user',
  unverifiedUser: 'unverified_user',
  profile: 'profile',
  follow: 'follow',
  post: 'post',
  reaction: 'reaction',
  media: 'media',
  mediaTemp: 'media_temp',
  postStats: 'post_stats',
  group: 'group',
  groupMember: 'group_member',
  tag: 'tag',
  thread: 'thread',
  threadFollow: 'thread_follow',
  notification: 'notification',
  chatChannel: 'chat_channel',
  chatMessage: 'chat_message',
  channelLastSeen: 'channel_last_seen',
} as const;
